//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.20 at 04:12:01 PM WAT 
//


package co.unitel.soapwebservice_funcionario;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.unitel.soapwebservice_funcionario package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.unitel.soapwebservice_funcionario
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetFuncionariosResponse }
     * 
     */
    public GetFuncionariosResponse createGetFuncionariosResponse() {
        return new GetFuncionariosResponse();
    }

    /**
     * Create an instance of {@link FuncionarioGet }
     * 
     */
    public FuncionarioGet createFuncionarioGet() {
        return new FuncionarioGet();
    }

    /**
     * Create an instance of {@link FindFuncionarioRequest }
     * 
     */
    public FindFuncionarioRequest createFindFuncionarioRequest() {
        return new FindFuncionarioRequest();
    }

    /**
     * Create an instance of {@link EliminarFuncionarioRequest }
     * 
     */
    public EliminarFuncionarioRequest createEliminarFuncionarioRequest() {
        return new EliminarFuncionarioRequest();
    }

    /**
     * Create an instance of {@link UpdateFuncionarioRequest }
     * 
     */
    public UpdateFuncionarioRequest createUpdateFuncionarioRequest() {
        return new UpdateFuncionarioRequest();
    }

    /**
     * Create an instance of {@link AddFuncionarioRequest }
     * 
     */
    public AddFuncionarioRequest createAddFuncionarioRequest() {
        return new AddFuncionarioRequest();
    }

    /**
     * Create an instance of {@link Funcionario }
     * 
     */
    public Funcionario createFuncionario() {
        return new Funcionario();
    }

    /**
     * Create an instance of {@link GetFuncionarioResponse }
     * 
     */
    public GetFuncionarioResponse createGetFuncionarioResponse() {
        return new GetFuncionarioResponse();
    }

    /**
     * Create an instance of {@link MensagemResponse }
     * 
     */
    public MensagemResponse createMensagemResponse() {
        return new MensagemResponse();
    }

    /**
     * Create an instance of {@link SucessoResponse }
     * 
     */
    public SucessoResponse createSucessoResponse() {
        return new SucessoResponse();
    }

    /**
     * Create an instance of {@link GetFuncionariosRequest }
     * 
     */
    public GetFuncionariosRequest createGetFuncionariosRequest() {
        return new GetFuncionariosRequest();
    }

}
