//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.20 at 04:12:01 PM WAT 
//


package co.unitel.soapwebservice_funcionario;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="funcionario" type="{http://unitel.co/soapwebservice_funcionario}funcionarioGet"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "funcionario"
})
@XmlRootElement(name = "updateFuncionarioRequest")
public class UpdateFuncionarioRequest {

    @XmlElement(required = true)
    protected FuncionarioGet funcionario;

    /**
     * Gets the value of the funcionario property.
     * 
     * @return
     *     possible object is
     *     {@link FuncionarioGet }
     *     
     */
    public FuncionarioGet getFuncionario() {
        return funcionario;
    }

    /**
     * Sets the value of the funcionario property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuncionarioGet }
     *     
     */
    public void setFuncionario(FuncionarioGet value) {
        this.funcionario = value;
    }

}
